apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: busybox
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - node2-pv
  containers:
    - name: busybox
      image: busybox:latest
  dnsPolicy: "None"
