apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: busybox
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - node3-pv
  containers:
    - name: busybox
      image: busybox:latest
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 192.168.178.1
    searches:
      - fritz.box
    options:
      - name: ndots
        value: "2"
      - name: edns0
