apiVersion: v1
kind: Pod
metadata:
  name: deconz
spec:
  hostNetwork: true
  nodeSelector:
    disktype: node2-pv
  volumes:
    - name: deconz-pv-storage
      persistentVolumeClaim:
        claimName: deconz-pvc
    - name: localtime
      hostPath:
        path: /etc/localtime:ro
    - name: ttyacm
      hostPath:
        path: /dev/ttyACM0
  containers:
    - name: deconz
      image: marthoc/deconz
      volumeMounts:
        - mountPath: "/opt/deconz"
          name: deconz-pv-storage
        - mountPath: "/etc/localtime"
          name: localtime
        - mountPath: /dev/ttyACM0
          name: ttyacm
          


