
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
switch: !include lka_files/switch.yaml
sensor: !include lka_files/cpu.yaml

recorder:
  exclude:
    entities:
      - sensor.cpu_temperature

