apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-hass-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.178.45 # replace with your nfs server IP or hostname
    path: "/media/usbdrive/hass" # replace with your mount path

