apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-hass-node3-pv
spec:
  capacity:
    storage: 5Gi
  storageClassName: "node3-pv"
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.178.45 # replace with your nfs server IP or hostname
    path: "/media/usbdrive/hass-node3" # replace with your mount path

